# Generated by Django 4.2.30 on 2026-04-26 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shelter_name", models.CharField(max_length=120)),
                ("location_label", models.CharField(blank=True, max_length=255)),
                ("geo_lat", models.CharField(blank=True, max_length=32)),
                ("geo_lon", models.CharField(blank=True, max_length=32)),
                ("location_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelter_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[("Dog", "Dog"), ("Cat", "Cat"), ("Other", "Other")],
                        max_length=20,
                    ),
                ),
                ("breed_name", models.CharField(max_length=80)),
                ("count", models.PositiveIntegerField(default=1)),
                ("zone", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="ngo_app.shelterprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["species", "breed_name", "zone", "-created_at"],
            },
        ),
    ]
