# Generated by Django 4.2.30 on 2026-04-27 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("milestone_points", models.PositiveIntegerField()),
                ("reward_name", models.CharField(max_length=120)),
                ("voucher_amount", models.PositiveIntegerField(default=0)),
                ("voucher_code", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("claimed", "Claimed")],
                        default="claimed",
                        max_length=20,
                    ),
                ),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-claimed_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="rewardclaim",
            constraint=models.UniqueConstraint(
                fields=("user", "milestone_points"),
                name="unique_reward_claim_per_user_per_milestone",
            ),
        ),
    ]
